### ISSUE TITLE
Trunctiation works differnetly

### ISSUE THREAD

**Issue by flytoe** [KevinGutowski/Truncat#3]
Hey great tool!
But I noticed a typo ;)

A distance is set both before and after the ellipsis points in sentences. Exception: The dots indicate that part of the word is omitted: "You A…!"

**Comment by KevinGutowski** [comment]
Hi, thanks for trying out the plugin. I don't quite understand what you are talking about. Could you clarify what type you are talking about? Perhaps a reference to the line of code? Thanks!

**Comment by flytoe** [comment]
Hi its not about the code its how its applied. There needs to be a space inbetween trunctuation and the text. http://guidetogrammar.org/grammar/marks/ellipsis.htm

**Comment by KevinGutowski** [comment]
Ahh I see now. Unfortunately, that’s now how its been implemented across MacOS, iOS, and even the web.

### MacOS
<img width="1283" alt="Screen Shot 2019-08-10 at 9 54 36 AM" src="https://user-images.githubusercontent.com/4199296/62824637-e92a7980-bb55-11e9-9c9d-6e68225cb42e.png">

### iOS
![IMG_1830](https://user-images.githubusercontent.com/4199296/62824629-cac47e00-bb55-11e9-989e-253e26c45855.PNG)

### Web
<img width="243" alt="Screen Shot 2019-08-10 at 9 54 58 AM" src="https://user-images.githubusercontent.com/4199296/62824633-d9ab3080-bb55-11e9-88a4-71428819be69.png">

—

Moreover, the ellipsis in the context that you are talking about is 
> … a handy device when you're quoting material and you want to omit some words.

However, in the context of app development, it's used to indicate that there is more content. It’s not a citation and it's not being used for editing purposes. If you want to achieve the kind of effect that you are looking for its imperative to manually insert the ellipsis so that your citation makes sense. 

Thanks for the feedback and the English lesson!
